### ISSUE TITLE
supported version of cuda ?

### ISSUE THREAD

**Issue by hjain28** [SciRuby/rbcuda#10]
is rbcuda compatible with cuda-10.1..105 ?

getting this error :

cd tmp/x86_64-linux-gnu/rbcuda/2.5.1
/usr/bin/make
compiling ../../../../ext/rbcuda/rbcuda.cpp
In file included from ../../../../ext/rbcuda/ruby_rbcuda.c:1967:0,
                 from ../../../../ext/rbcuda/rbcuda.cpp:31:
../../../../ext/rbcuda/internals/cuda_runtime_api.c: In function ‘VALUE rb_cudaLaunch(VALUE, VALUE)’:
../../../../ext/rbcuda/internals/cuda_runtime_api.c:1013:21: error: ‘cudaLaunch’ was not declared in this scope
   cudaError error = cudaLaunch((void*)func);
                     ^~~~~~~~~~
../../../../ext/rbcuda/internals/cuda_runtime_api.c:1013:21: note: suggested alternative: ‘cuLaunch’
   cudaError error = cudaLaunch((void*)func);
                     ^~~~~~~~~~
                     cuLaunch
Makefile:240: recipe for target 'rbcuda.o' failed
make: *** [rbcuda.o] Error 1
rake aborted!
Command failed with status (2): [/usr/bin/make...]
/var/lib/gems/2.5.0/gems/rake-compiler-0.9.9/lib/rake/extensiontask.rb:157:in `block (2 levels) in define_compile_tasks'
/var/lib/gems/2.5.0/gems/rake-compiler-0.9.9/lib/rake/extensiontask.rb:156:in `block in define_compile_tasks'
/usr/share/rubygems-integration/all/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => compile => compile:x86_64-linux-gnu => compile:rbcuda:x86_64-linux-gnu => copy:rbcuda:x86_64-linux-gnu:2.5.1 => tmp/x86_64-linux-gnu/rbcuda/2.5.1/rbcuda.so
(See full trace by running task with --trace

**Comment by WinnieHAN** [comment]
Same bug.
